---
- name: import+ delegate_to
  hosts: ubuntu2004
  become: yes

  vars:
   mytext: "hello"

  tasks:
  - name: unregister Server from load balancer
    shell: echo this server {{inventory_hostname }} was deregistered from our load balancer, node name is {{ansible_nodename }} >> /home/log.txt
    delegate_to: 127.0.0.1

  - name: ping test
    ping:
    delegate_to: ubuntu2004                   #запуск тільки на ubuntu2004

  - import_tasks: folders.yml
  - import_tasks: files.yml

  - name: reboot my server
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: wait till my server will come up online
    wait_for:
        host: "{{ inventory_hostname }}"
        state: started
        delay: 5
        timeout: 40
    delegate_to: 127.0.0.1
