---
- name: loops playbook
  hosts: ubuntu2004
  become: yes

  tasks:
  - name: say hello to all
    debug: msg="hello {{ item }}"
    loop:
     - "Anrii"
     - "Denis"
     - "Misha"

  - name: loop untill example
    shell: echo -n z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("zzzz") == false

  - name: print final output
    debug:
      var: output.stdout

#  - name: install many packaged
#    apt: name={{ item }} state=installed
#    loop:
#      - python
#      - mysql
#      - program3
